//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwipCardSystem.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="org.isms.server.server", ConfigurationName="ServiceReference2.TerminalService")]
    public interface TerminalService {
        
        // CODEGEN: 命名空间  的元素名称 inputJson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SwipCardSystem.ServiceReference2.grouptreeResponse grouptree(SwipCardSystem.ServiceReference2.grouptree request);
        
        // CODEGEN: 命名空间  的元素名称 inputJson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SwipCardSystem.ServiceReference2.parentinfoallResponse parentinfoall(SwipCardSystem.ServiceReference2.parentinfoall request);
        
        // CODEGEN: 命名空间  的元素名称 inputJson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SwipCardSystem.ServiceReference2.parentpicResponse parentpic(SwipCardSystem.ServiceReference2.parentpic request);
        
        // CODEGEN: 命名空间  的元素名称 inputJson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SwipCardSystem.ServiceReference2.checkononeResponse checkonone(SwipCardSystem.ServiceReference2.checkonone request);
        
        // CODEGEN: 命名空间  的元素名称 inputJson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SwipCardSystem.ServiceReference2.iccardinfoallResponse iccardinfoall(SwipCardSystem.ServiceReference2.iccardinfoall request);
        
        // CODEGEN: 命名空间  的元素名称 inputJson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SwipCardSystem.ServiceReference2.newnoticeinfoResponse newnoticeinfo(SwipCardSystem.ServiceReference2.newnoticeinfo request);
        
        // CODEGEN: 命名空间  的元素名称 inputJson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SwipCardSystem.ServiceReference2.parentinfoaddResponse parentinfoadd(SwipCardSystem.ServiceReference2.parentinfoadd request);
        
        // CODEGEN: 命名空间  的元素名称 inputJson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SwipCardSystem.ServiceReference2.checkonbatchResponse checkonbatch(SwipCardSystem.ServiceReference2.checkonbatch request);
        
        // CODEGEN: 命名空间  的元素名称 inputJson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SwipCardSystem.ServiceReference2.iccardinfoaddResponse iccardinfoadd(SwipCardSystem.ServiceReference2.iccardinfoadd request);
        
        // CODEGEN: 命名空间  的元素名称 inputJson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SwipCardSystem.ServiceReference2.studentpicResponse studentpic(SwipCardSystem.ServiceReference2.studentpic request);
        
        // CODEGEN: 命名空间  的元素名称 inputJson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SwipCardSystem.ServiceReference2.checkonpicResponse checkonpic(SwipCardSystem.ServiceReference2.checkonpic request);
        
        // CODEGEN: 命名空间  的元素名称 inputJson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SwipCardSystem.ServiceReference2.studentsinfoallResponse studentsinfoall(SwipCardSystem.ServiceReference2.studentsinfoall request);
        
        // CODEGEN: 命名空间  的元素名称 inputJson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SwipCardSystem.ServiceReference2.studentsinfoaddResponse studentsinfoadd(SwipCardSystem.ServiceReference2.studentsinfoadd request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class grouptree {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="grouptree", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.grouptreeBody Body;
        
        public grouptree() {
        }
        
        public grouptree(SwipCardSystem.ServiceReference2.grouptreeBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class grouptreeBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputJson;
        
        public grouptreeBody() {
        }
        
        public grouptreeBody(string inputJson) {
            this.inputJson = inputJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class grouptreeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="grouptreeResponse", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.grouptreeResponseBody Body;
        
        public grouptreeResponse() {
        }
        
        public grouptreeResponse(SwipCardSystem.ServiceReference2.grouptreeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="org.isms.server.server")]
    public partial class grouptreeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnJson;
        
        public grouptreeResponseBody() {
        }
        
        public grouptreeResponseBody(string returnJson) {
            this.returnJson = returnJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class parentinfoall {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="parentinfoall", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.parentinfoallBody Body;
        
        public parentinfoall() {
        }
        
        public parentinfoall(SwipCardSystem.ServiceReference2.parentinfoallBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class parentinfoallBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputJson;
        
        public parentinfoallBody() {
        }
        
        public parentinfoallBody(string inputJson) {
            this.inputJson = inputJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class parentinfoallResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="parentinfoallResponse", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.parentinfoallResponseBody Body;
        
        public parentinfoallResponse() {
        }
        
        public parentinfoallResponse(SwipCardSystem.ServiceReference2.parentinfoallResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="org.isms.server.server")]
    public partial class parentinfoallResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnJson;
        
        public parentinfoallResponseBody() {
        }
        
        public parentinfoallResponseBody(string returnJson) {
            this.returnJson = returnJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class parentpic {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="parentpic", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.parentpicBody Body;
        
        public parentpic() {
        }
        
        public parentpic(SwipCardSystem.ServiceReference2.parentpicBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class parentpicBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputJson;
        
        public parentpicBody() {
        }
        
        public parentpicBody(string inputJson) {
            this.inputJson = inputJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class parentpicResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="parentpicResponse", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.parentpicResponseBody Body;
        
        public parentpicResponse() {
        }
        
        public parentpicResponse(SwipCardSystem.ServiceReference2.parentpicResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="org.isms.server.server")]
    public partial class parentpicResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnJson;
        
        public parentpicResponseBody() {
        }
        
        public parentpicResponseBody(string returnJson) {
            this.returnJson = returnJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkonone {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkonone", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.checkononeBody Body;
        
        public checkonone() {
        }
        
        public checkonone(SwipCardSystem.ServiceReference2.checkononeBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class checkononeBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputJson;
        
        public checkononeBody() {
        }
        
        public checkononeBody(string inputJson) {
            this.inputJson = inputJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkononeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkononeResponse", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.checkononeResponseBody Body;
        
        public checkononeResponse() {
        }
        
        public checkononeResponse(SwipCardSystem.ServiceReference2.checkononeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="org.isms.server.server")]
    public partial class checkononeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnJson;
        
        public checkononeResponseBody() {
        }
        
        public checkononeResponseBody(string returnJson) {
            this.returnJson = returnJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class iccardinfoall {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="iccardinfoall", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.iccardinfoallBody Body;
        
        public iccardinfoall() {
        }
        
        public iccardinfoall(SwipCardSystem.ServiceReference2.iccardinfoallBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class iccardinfoallBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputJson;
        
        public iccardinfoallBody() {
        }
        
        public iccardinfoallBody(string inputJson) {
            this.inputJson = inputJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class iccardinfoallResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="iccardinfoallResponse", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.iccardinfoallResponseBody Body;
        
        public iccardinfoallResponse() {
        }
        
        public iccardinfoallResponse(SwipCardSystem.ServiceReference2.iccardinfoallResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="org.isms.server.server")]
    public partial class iccardinfoallResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnJson;
        
        public iccardinfoallResponseBody() {
        }
        
        public iccardinfoallResponseBody(string returnJson) {
            this.returnJson = returnJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class newnoticeinfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="newnoticeinfo", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.newnoticeinfoBody Body;
        
        public newnoticeinfo() {
        }
        
        public newnoticeinfo(SwipCardSystem.ServiceReference2.newnoticeinfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class newnoticeinfoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputJson;
        
        public newnoticeinfoBody() {
        }
        
        public newnoticeinfoBody(string inputJson) {
            this.inputJson = inputJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class newnoticeinfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="newnoticeinfoResponse", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.newnoticeinfoResponseBody Body;
        
        public newnoticeinfoResponse() {
        }
        
        public newnoticeinfoResponse(SwipCardSystem.ServiceReference2.newnoticeinfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="org.isms.server.server")]
    public partial class newnoticeinfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnJson;
        
        public newnoticeinfoResponseBody() {
        }
        
        public newnoticeinfoResponseBody(string returnJson) {
            this.returnJson = returnJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class parentinfoadd {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="parentinfoadd", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.parentinfoaddBody Body;
        
        public parentinfoadd() {
        }
        
        public parentinfoadd(SwipCardSystem.ServiceReference2.parentinfoaddBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class parentinfoaddBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputJson;
        
        public parentinfoaddBody() {
        }
        
        public parentinfoaddBody(string inputJson) {
            this.inputJson = inputJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class parentinfoaddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="parentinfoaddResponse", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.parentinfoaddResponseBody Body;
        
        public parentinfoaddResponse() {
        }
        
        public parentinfoaddResponse(SwipCardSystem.ServiceReference2.parentinfoaddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="org.isms.server.server")]
    public partial class parentinfoaddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnJson;
        
        public parentinfoaddResponseBody() {
        }
        
        public parentinfoaddResponseBody(string returnJson) {
            this.returnJson = returnJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkonbatch {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkonbatch", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.checkonbatchBody Body;
        
        public checkonbatch() {
        }
        
        public checkonbatch(SwipCardSystem.ServiceReference2.checkonbatchBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class checkonbatchBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputJson;
        
        public checkonbatchBody() {
        }
        
        public checkonbatchBody(string inputJson) {
            this.inputJson = inputJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkonbatchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkonbatchResponse", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.checkonbatchResponseBody Body;
        
        public checkonbatchResponse() {
        }
        
        public checkonbatchResponse(SwipCardSystem.ServiceReference2.checkonbatchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="org.isms.server.server")]
    public partial class checkonbatchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnJson;
        
        public checkonbatchResponseBody() {
        }
        
        public checkonbatchResponseBody(string returnJson) {
            this.returnJson = returnJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class iccardinfoadd {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="iccardinfoadd", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.iccardinfoaddBody Body;
        
        public iccardinfoadd() {
        }
        
        public iccardinfoadd(SwipCardSystem.ServiceReference2.iccardinfoaddBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class iccardinfoaddBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputJson;
        
        public iccardinfoaddBody() {
        }
        
        public iccardinfoaddBody(string inputJson) {
            this.inputJson = inputJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class iccardinfoaddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="iccardinfoaddResponse", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.iccardinfoaddResponseBody Body;
        
        public iccardinfoaddResponse() {
        }
        
        public iccardinfoaddResponse(SwipCardSystem.ServiceReference2.iccardinfoaddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="org.isms.server.server")]
    public partial class iccardinfoaddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnJson;
        
        public iccardinfoaddResponseBody() {
        }
        
        public iccardinfoaddResponseBody(string returnJson) {
            this.returnJson = returnJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class studentpic {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="studentpic", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.studentpicBody Body;
        
        public studentpic() {
        }
        
        public studentpic(SwipCardSystem.ServiceReference2.studentpicBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class studentpicBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputJson;
        
        public studentpicBody() {
        }
        
        public studentpicBody(string inputJson) {
            this.inputJson = inputJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class studentpicResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="studentpicResponse", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.studentpicResponseBody Body;
        
        public studentpicResponse() {
        }
        
        public studentpicResponse(SwipCardSystem.ServiceReference2.studentpicResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="org.isms.server.server")]
    public partial class studentpicResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnJson;
        
        public studentpicResponseBody() {
        }
        
        public studentpicResponseBody(string returnJson) {
            this.returnJson = returnJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkonpic {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkonpic", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.checkonpicBody Body;
        
        public checkonpic() {
        }
        
        public checkonpic(SwipCardSystem.ServiceReference2.checkonpicBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class checkonpicBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputJson;
        
        public checkonpicBody() {
        }
        
        public checkonpicBody(string inputJson) {
            this.inputJson = inputJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkonpicResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkonpicResponse", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.checkonpicResponseBody Body;
        
        public checkonpicResponse() {
        }
        
        public checkonpicResponse(SwipCardSystem.ServiceReference2.checkonpicResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="org.isms.server.server")]
    public partial class checkonpicResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnJson;
        
        public checkonpicResponseBody() {
        }
        
        public checkonpicResponseBody(string returnJson) {
            this.returnJson = returnJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class studentsinfoall {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="studentsinfoall", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.studentsinfoallBody Body;
        
        public studentsinfoall() {
        }
        
        public studentsinfoall(SwipCardSystem.ServiceReference2.studentsinfoallBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class studentsinfoallBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputJson;
        
        public studentsinfoallBody() {
        }
        
        public studentsinfoallBody(string inputJson) {
            this.inputJson = inputJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class studentsinfoallResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="studentsinfoallResponse", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.studentsinfoallResponseBody Body;
        
        public studentsinfoallResponse() {
        }
        
        public studentsinfoallResponse(SwipCardSystem.ServiceReference2.studentsinfoallResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="org.isms.server.server")]
    public partial class studentsinfoallResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnJson;
        
        public studentsinfoallResponseBody() {
        }
        
        public studentsinfoallResponseBody(string returnJson) {
            this.returnJson = returnJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class studentsinfoadd {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="studentsinfoadd", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.studentsinfoaddBody Body;
        
        public studentsinfoadd() {
        }
        
        public studentsinfoadd(SwipCardSystem.ServiceReference2.studentsinfoaddBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class studentsinfoaddBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputJson;
        
        public studentsinfoaddBody() {
        }
        
        public studentsinfoaddBody(string inputJson) {
            this.inputJson = inputJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class studentsinfoaddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="studentsinfoaddResponse", Namespace="org.isms.server.server", Order=0)]
        public SwipCardSystem.ServiceReference2.studentsinfoaddResponseBody Body;
        
        public studentsinfoaddResponse() {
        }
        
        public studentsinfoaddResponse(SwipCardSystem.ServiceReference2.studentsinfoaddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="org.isms.server.server")]
    public partial class studentsinfoaddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnJson;
        
        public studentsinfoaddResponseBody() {
        }
        
        public studentsinfoaddResponseBody(string returnJson) {
            this.returnJson = returnJson;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TerminalServiceChannel : SwipCardSystem.ServiceReference2.TerminalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TerminalServiceClient : System.ServiceModel.ClientBase<SwipCardSystem.ServiceReference2.TerminalService>, SwipCardSystem.ServiceReference2.TerminalService {
        
        public TerminalServiceClient() {
        }
        
        public TerminalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TerminalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TerminalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TerminalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SwipCardSystem.ServiceReference2.grouptreeResponse SwipCardSystem.ServiceReference2.TerminalService.grouptree(SwipCardSystem.ServiceReference2.grouptree request) {
            return base.Channel.grouptree(request);
        }
        
        public string grouptree(string inputJson) {
            SwipCardSystem.ServiceReference2.grouptree inValue = new SwipCardSystem.ServiceReference2.grouptree();
            inValue.Body = new SwipCardSystem.ServiceReference2.grouptreeBody();
            inValue.Body.inputJson = inputJson;
            SwipCardSystem.ServiceReference2.grouptreeResponse retVal = ((SwipCardSystem.ServiceReference2.TerminalService)(this)).grouptree(inValue);
            return retVal.Body.returnJson;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SwipCardSystem.ServiceReference2.parentinfoallResponse SwipCardSystem.ServiceReference2.TerminalService.parentinfoall(SwipCardSystem.ServiceReference2.parentinfoall request) {
            return base.Channel.parentinfoall(request);
        }
        
        public string parentinfoall(string inputJson) {
            SwipCardSystem.ServiceReference2.parentinfoall inValue = new SwipCardSystem.ServiceReference2.parentinfoall();
            inValue.Body = new SwipCardSystem.ServiceReference2.parentinfoallBody();
            inValue.Body.inputJson = inputJson;
            SwipCardSystem.ServiceReference2.parentinfoallResponse retVal = ((SwipCardSystem.ServiceReference2.TerminalService)(this)).parentinfoall(inValue);
            return retVal.Body.returnJson;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SwipCardSystem.ServiceReference2.parentpicResponse SwipCardSystem.ServiceReference2.TerminalService.parentpic(SwipCardSystem.ServiceReference2.parentpic request) {
            return base.Channel.parentpic(request);
        }
        
        public string parentpic(string inputJson) {
            SwipCardSystem.ServiceReference2.parentpic inValue = new SwipCardSystem.ServiceReference2.parentpic();
            inValue.Body = new SwipCardSystem.ServiceReference2.parentpicBody();
            inValue.Body.inputJson = inputJson;
            SwipCardSystem.ServiceReference2.parentpicResponse retVal = ((SwipCardSystem.ServiceReference2.TerminalService)(this)).parentpic(inValue);
            return retVal.Body.returnJson;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SwipCardSystem.ServiceReference2.checkononeResponse SwipCardSystem.ServiceReference2.TerminalService.checkonone(SwipCardSystem.ServiceReference2.checkonone request) {
            return base.Channel.checkonone(request);
        }
        
        public string checkonone(string inputJson) {
            SwipCardSystem.ServiceReference2.checkonone inValue = new SwipCardSystem.ServiceReference2.checkonone();
            inValue.Body = new SwipCardSystem.ServiceReference2.checkononeBody();
            inValue.Body.inputJson = inputJson;
            SwipCardSystem.ServiceReference2.checkononeResponse retVal = ((SwipCardSystem.ServiceReference2.TerminalService)(this)).checkonone(inValue);
            return retVal.Body.returnJson;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SwipCardSystem.ServiceReference2.iccardinfoallResponse SwipCardSystem.ServiceReference2.TerminalService.iccardinfoall(SwipCardSystem.ServiceReference2.iccardinfoall request) {
            return base.Channel.iccardinfoall(request);
        }
        
        public string iccardinfoall(string inputJson) {
            SwipCardSystem.ServiceReference2.iccardinfoall inValue = new SwipCardSystem.ServiceReference2.iccardinfoall();
            inValue.Body = new SwipCardSystem.ServiceReference2.iccardinfoallBody();
            inValue.Body.inputJson = inputJson;
            SwipCardSystem.ServiceReference2.iccardinfoallResponse retVal = ((SwipCardSystem.ServiceReference2.TerminalService)(this)).iccardinfoall(inValue);
            return retVal.Body.returnJson;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SwipCardSystem.ServiceReference2.newnoticeinfoResponse SwipCardSystem.ServiceReference2.TerminalService.newnoticeinfo(SwipCardSystem.ServiceReference2.newnoticeinfo request) {
            return base.Channel.newnoticeinfo(request);
        }
        
        public string newnoticeinfo(string inputJson) {
            SwipCardSystem.ServiceReference2.newnoticeinfo inValue = new SwipCardSystem.ServiceReference2.newnoticeinfo();
            inValue.Body = new SwipCardSystem.ServiceReference2.newnoticeinfoBody();
            inValue.Body.inputJson = inputJson;
            SwipCardSystem.ServiceReference2.newnoticeinfoResponse retVal = ((SwipCardSystem.ServiceReference2.TerminalService)(this)).newnoticeinfo(inValue);
            return retVal.Body.returnJson;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SwipCardSystem.ServiceReference2.parentinfoaddResponse SwipCardSystem.ServiceReference2.TerminalService.parentinfoadd(SwipCardSystem.ServiceReference2.parentinfoadd request) {
            return base.Channel.parentinfoadd(request);
        }
        
        public string parentinfoadd(string inputJson) {
            SwipCardSystem.ServiceReference2.parentinfoadd inValue = new SwipCardSystem.ServiceReference2.parentinfoadd();
            inValue.Body = new SwipCardSystem.ServiceReference2.parentinfoaddBody();
            inValue.Body.inputJson = inputJson;
            SwipCardSystem.ServiceReference2.parentinfoaddResponse retVal = ((SwipCardSystem.ServiceReference2.TerminalService)(this)).parentinfoadd(inValue);
            return retVal.Body.returnJson;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SwipCardSystem.ServiceReference2.checkonbatchResponse SwipCardSystem.ServiceReference2.TerminalService.checkonbatch(SwipCardSystem.ServiceReference2.checkonbatch request) {
            return base.Channel.checkonbatch(request);
        }
        
        public string checkonbatch(string inputJson) {
            SwipCardSystem.ServiceReference2.checkonbatch inValue = new SwipCardSystem.ServiceReference2.checkonbatch();
            inValue.Body = new SwipCardSystem.ServiceReference2.checkonbatchBody();
            inValue.Body.inputJson = inputJson;
            SwipCardSystem.ServiceReference2.checkonbatchResponse retVal = ((SwipCardSystem.ServiceReference2.TerminalService)(this)).checkonbatch(inValue);
            return retVal.Body.returnJson;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SwipCardSystem.ServiceReference2.iccardinfoaddResponse SwipCardSystem.ServiceReference2.TerminalService.iccardinfoadd(SwipCardSystem.ServiceReference2.iccardinfoadd request) {
            return base.Channel.iccardinfoadd(request);
        }
        
        public string iccardinfoadd(string inputJson) {
            SwipCardSystem.ServiceReference2.iccardinfoadd inValue = new SwipCardSystem.ServiceReference2.iccardinfoadd();
            inValue.Body = new SwipCardSystem.ServiceReference2.iccardinfoaddBody();
            inValue.Body.inputJson = inputJson;
            SwipCardSystem.ServiceReference2.iccardinfoaddResponse retVal = ((SwipCardSystem.ServiceReference2.TerminalService)(this)).iccardinfoadd(inValue);
            return retVal.Body.returnJson;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SwipCardSystem.ServiceReference2.studentpicResponse SwipCardSystem.ServiceReference2.TerminalService.studentpic(SwipCardSystem.ServiceReference2.studentpic request) {
            return base.Channel.studentpic(request);
        }
        
        public string studentpic(string inputJson) {
            SwipCardSystem.ServiceReference2.studentpic inValue = new SwipCardSystem.ServiceReference2.studentpic();
            inValue.Body = new SwipCardSystem.ServiceReference2.studentpicBody();
            inValue.Body.inputJson = inputJson;
            SwipCardSystem.ServiceReference2.studentpicResponse retVal = ((SwipCardSystem.ServiceReference2.TerminalService)(this)).studentpic(inValue);
            return retVal.Body.returnJson;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SwipCardSystem.ServiceReference2.checkonpicResponse SwipCardSystem.ServiceReference2.TerminalService.checkonpic(SwipCardSystem.ServiceReference2.checkonpic request) {
            return base.Channel.checkonpic(request);
        }
        
        public string checkonpic(string inputJson) {
            SwipCardSystem.ServiceReference2.checkonpic inValue = new SwipCardSystem.ServiceReference2.checkonpic();
            inValue.Body = new SwipCardSystem.ServiceReference2.checkonpicBody();
            inValue.Body.inputJson = inputJson;
            SwipCardSystem.ServiceReference2.checkonpicResponse retVal = ((SwipCardSystem.ServiceReference2.TerminalService)(this)).checkonpic(inValue);
            return retVal.Body.returnJson;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SwipCardSystem.ServiceReference2.studentsinfoallResponse SwipCardSystem.ServiceReference2.TerminalService.studentsinfoall(SwipCardSystem.ServiceReference2.studentsinfoall request) {
            return base.Channel.studentsinfoall(request);
        }
        
        public string studentsinfoall(string inputJson) {
            SwipCardSystem.ServiceReference2.studentsinfoall inValue = new SwipCardSystem.ServiceReference2.studentsinfoall();
            inValue.Body = new SwipCardSystem.ServiceReference2.studentsinfoallBody();
            inValue.Body.inputJson = inputJson;
            SwipCardSystem.ServiceReference2.studentsinfoallResponse retVal = ((SwipCardSystem.ServiceReference2.TerminalService)(this)).studentsinfoall(inValue);
            return retVal.Body.returnJson;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SwipCardSystem.ServiceReference2.studentsinfoaddResponse SwipCardSystem.ServiceReference2.TerminalService.studentsinfoadd(SwipCardSystem.ServiceReference2.studentsinfoadd request) {
            return base.Channel.studentsinfoadd(request);
        }
        
        public string studentsinfoadd(string inputJson) {
            SwipCardSystem.ServiceReference2.studentsinfoadd inValue = new SwipCardSystem.ServiceReference2.studentsinfoadd();
            inValue.Body = new SwipCardSystem.ServiceReference2.studentsinfoaddBody();
            inValue.Body.inputJson = inputJson;
            SwipCardSystem.ServiceReference2.studentsinfoaddResponse retVal = ((SwipCardSystem.ServiceReference2.TerminalService)(this)).studentsinfoadd(inValue);
            return retVal.Body.returnJson;
        }
    }
}
